// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNV.Data;

#nullable disable

namespace QLNV.Migrations
{
    [DbContext(typeof(QLNVDbContext))]
    [Migration("20250914133848_addData")]
    partial class addData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNV.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 21,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 22,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 23,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 24,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 25,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 26,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 27,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 28,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 29,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 30,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 31,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 32,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 33,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 34,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 35,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 36,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 37,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 38,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 39,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 40,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 41,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 42,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 43,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 44,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 45,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 46,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 47,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 48,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 49,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 50,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 52,
                            Age = 35,
                            DateOfBirth = new DateTime(1990, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kỹ Thuật",
                            FullName = "Hùng",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            EmployeeId = 53,
                            Age = 27,
                            DateOfBirth = new DateTime(1998, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Nhân Sự",
                            FullName = "Mai",
                            PhoneNumber = "0934567890"
                        },
                        new
                        {
                            EmployeeId = 54,
                            Age = 33,
                            DateOfBirth = new DateTime(1992, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "Tuấn",
                            PhoneNumber = "0976543210"
                        },
                        new
                        {
                            EmployeeId = 55,
                            Age = 29,
                            DateOfBirth = new DateTime(1996, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Hạnh",
                            PhoneNumber = "0901122334"
                        },
                        new
                        {
                            EmployeeId = 56,
                            Age = 31,
                            DateOfBirth = new DateTime(1994, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kỹ Thuật",
                            FullName = "Sơn",
                            PhoneNumber = "0988123456"
                        },
                        new
                        {
                            EmployeeId = 57,
                            Age = 34,
                            DateOfBirth = new DateTime(1991, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kế Toán",
                            FullName = "Vân",
                            PhoneNumber = "0911765432"
                        },
                        new
                        {
                            EmployeeId = 58,
                            Age = 32,
                            DateOfBirth = new DateTime(1993, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Nhân Sự",
                            FullName = "Nam",
                            PhoneNumber = "0923456789"
                        },
                        new
                        {
                            EmployeeId = 59,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "Ly",
                            PhoneNumber = "0954321987"
                        },
                        new
                        {
                            EmployeeId = 60,
                            Age = 26,
                            DateOfBirth = new DateTime(1999, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Quang",
                            PhoneNumber = "0965432109"
                        },
                        new
                        {
                            EmployeeId = 61,
                            Age = 30,
                            DateOfBirth = new DateTime(1995, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kỹ Thuật",
                            FullName = "Nga",
                            PhoneNumber = "0932112345"
                        },
                        new
                        {
                            EmployeeId = 62,
                            Age = 36,
                            DateOfBirth = new DateTime(1989, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kế Toán",
                            FullName = "Phong",
                            PhoneNumber = "0909876543"
                        },
                        new
                        {
                            EmployeeId = 63,
                            Age = 31,
                            DateOfBirth = new DateTime(1994, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Nhân Sự",
                            FullName = "Thu",
                            PhoneNumber = "0977334455"
                        },
                        new
                        {
                            EmployeeId = 64,
                            Age = 33,
                            DateOfBirth = new DateTime(1992, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "Kiên",
                            PhoneNumber = "0944556677"
                        },
                        new
                        {
                            EmployeeId = 65,
                            Age = 29,
                            DateOfBirth = new DateTime(1996, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Yến",
                            PhoneNumber = "0911223344"
                        },
                        new
                        {
                            EmployeeId = 66,
                            Age = 32,
                            DateOfBirth = new DateTime(1993, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kỹ Thuật",
                            FullName = "Đạt",
                            PhoneNumber = "0988445566"
                        },
                        new
                        {
                            EmployeeId = 67,
                            Age = 27,
                            DateOfBirth = new DateTime(1998, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Nhân Sự",
                            FullName = "Trang",
                            PhoneNumber = "0922334455"
                        },
                        new
                        {
                            EmployeeId = 68,
                            Age = 34,
                            DateOfBirth = new DateTime(1991, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kế Toán",
                            FullName = "Dũng",
                            PhoneNumber = "0955667788"
                        },
                        new
                        {
                            EmployeeId = 69,
                            Age = 35,
                            DateOfBirth = new DateTime(1990, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Hòa",
                            PhoneNumber = "0978990011"
                        },
                        new
                        {
                            EmployeeId = 70,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "Phúc",
                            PhoneNumber = "0933557799"
                        },
                        new
                        {
                            EmployeeId = 71,
                            Age = 26,
                            DateOfBirth = new DateTime(1999, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kỹ Thuật",
                            FullName = "Thảo",
                            PhoneNumber = "0911445566"
                        },
                        new
                        {
                            EmployeeId = 72,
                            Age = 30,
                            DateOfBirth = new DateTime(1995, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kế Toán",
                            FullName = "Cường",
                            PhoneNumber = "0921445566"
                        },
                        new
                        {
                            EmployeeId = 73,
                            Age = 32,
                            DateOfBirth = new DateTime(1993, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Nhân Sự",
                            FullName = "Ngọc",
                            PhoneNumber = "0944667788"
                        },
                        new
                        {
                            EmployeeId = 74,
                            Age = 33,
                            DateOfBirth = new DateTime(1992, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Lâm",
                            PhoneNumber = "0966998877"
                        },
                        new
                        {
                            EmployeeId = 75,
                            Age = 27,
                            DateOfBirth = new DateTime(1998, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "Hải",
                            PhoneNumber = "0907788990"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
