// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNV.Data;

#nullable disable

namespace QLNV.Migrations
{
    [DbContext(typeof(QLNVDbContext))]
    [Migration("20250904162243_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNV.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 21,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 22,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 23,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 24,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 25,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 26,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 27,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 28,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 29,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 30,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 31,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 32,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 33,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 34,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 35,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 36,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 37,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 38,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 39,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 40,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 41,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 42,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 43,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 44,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 45,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 46,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 47,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 48,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 49,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            EmployeeId = 50,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sản Xuất",
                            FullName = "thịnh",
                            PhoneNumber = "0123456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
